name: Java CI

on:
  push:
    paths:
      - 'gradle.properties'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
      MAVEN_USER: ${{ secrets.MAVEN_USER }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
          
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Run the Gradle package task
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build

    - name: Get file name
      run: echo "file_path=$(ls build/libs/*)" >> $GITHUB_OUTPUT
      id: var

    - name: Upload to CurseForge
      uses: itsmeow/curseforge-upload@v3
      with:
        token: ${{ secrets.CURSEFORGE_TOKEN }}
        project_id: 604054
        game_endpoint: minecraft
        file_path: ${{ steps.var.outputs.file_path }}
        changelog: See recent commits [here](https://github.com/Low-Drag-MC/Multiblocked/commits/${{ github.sha }}). This is only marked as a beta release so CurseForge shows it on the front page.
        changelog_type: markdown
        # 1.12.2, Java 8
        game_versions: "Minecraft 1.18:1.18.2,Java 17,Forge"
        release_type: beta
        relations: ldlibl:requiredDependency,geckolib:optionalDependency,jei:optionalDependency,roughly-enough-items:optionalDependency
